from __future__ import annotations

from .cli.installer import (
    DEFAULT_CONFIG,
    LEGACY_PLUGIN_NAME,
    PLUGIN_NAME,
    InstallResult,
    _advanced_install_overrides,
    _apply_config_overrides,
    _backup_config,
    _builtin_reasoning_conflict,
    _confirm,
    _copy_plugin,
    _default_source_dir,
    _discover_profile_names,
    _generated_plugin_yaml,
    _interactive_install_options,
    _is_package_source_dir,
    _is_plugin_source_dir,
    _merge_missing_defaults,
    _migrate_legacy_config,
    _parse_profile_list,
    _prompt,
    _prompt_setup_mode,
    _read_yaml,
    _reasoning_tail_enabled,
    _resolve_profile_targets,
    _select_profiles_interactive,
    _simple_install_overrides,
    _update_config,
    _write_yaml,
    install,
    install_many,
    main,
    uninstall,
    uninstall_many,
)

__all__ = [
    "PLUGIN_NAME",
    "LEGACY_PLUGIN_NAME",
    "DEFAULT_CONFIG",
    "InstallResult",
    "_read_yaml",
    "_write_yaml",
    "_discover_profile_names",
    "_resolve_profile_targets",
    "_backup_config",
    "_copy_plugin",
    "_is_plugin_source_dir",
    "_is_package_source_dir",
    "_generated_plugin_yaml",
    "_default_source_dir",
    "_migrate_legacy_config",
    "_reasoning_tail_enabled",
    "_builtin_reasoning_conflict",
    "_merge_missing_defaults",
    "_apply_config_overrides",
    "_update_config",
    "install",
    "install_many",
    "uninstall",
    "uninstall_many",
    "_parse_profile_list",
    "_prompt",
    "_prompt_setup_mode",
    "_confirm",
    "_select_profiles_interactive",
    "_simple_install_overrides",
    "_advanced_install_overrides",
    "_interactive_install_options",
    "main",
]

if __name__ == "__main__":
    raise SystemExit(main())
