from __future__ import annotations

from typing import Any

VALID_STRATEGIES = {"auto", "live_tail", "snapshot", "summary_only", "off"}
BATCH_DEFAULT_OFF = {"email", "sms", "webhook", "homeassistant"}
RETIRED_CONFIG_KEYS = {
    "progress_tail.finalization",
    "progress_tail.background_jobs.default_notify_on_complete",
    "progress_tail.telegram.collapsible_details",
    "progress_tail.telegram.details_open_on_failure",
}
PROGRESS_TAIL_CONFIG_CONTRACT: dict[str, Any] = {
    "enabled": None,
    "tools": {
        "enabled": None,
        "lines": None,
        "preview_length": None,
        "show_completed": None,
        "show_duration": None,
        "timestamp": None,
        "timestamp_format": None,
    },
    "delegates": {
        "enabled": None,
        "max_delegates": None,
        "lines_per_delegate": None,
        "max_goal_chars": None,
        "max_line_chars": None,
        "show_model": None,
        "show_tool_count": None,
        "show_completion": None,
        "completed_ttl_seconds": None,
        "thinking": None,
    },
    "todo": {
        "sticky": None,
        "hide_tool_line": None,
        "max_pending": None,
        "max_completed": None,
        "max_cancelled": None,
        "max_item_chars": None,
    },
    "patch": {"detail": None, "preview_chars": None, "max_files": None},
    "assistant": {"enabled": None, "max_lines": None, "max_chars": None, "min_update_chars": None},
    "reasoning": {
        "enabled": None,
        "max_lines": None,
        "max_chars": None,
        "min_update_chars": None,
        "no_edit_strategy": None,
    },
    "background_jobs": {
        "enabled": None,
        "list_running": None,
        "show_completed": None,
        "completed_ttl_seconds": None,
        "max_jobs": None,
        "head_lines": None,
        "tail_lines": None,
        "max_line_chars": None,
        "update_interval_seconds": None,
        "suppress_native_notify": None,
        "suppress_watch_notifications": None,
    },
    "native_gateway": {
        "suppress": None,
    },
    "cleanup": {
        "auto_delete": None,
        "delay_seconds": None,
        "delete_on_success": None,
        "delete_on_failure": None,
        "delete_background_active": None,
    },
    "footer": {
        "enabled": None,
        "density": None,
        "max_path_chars": None,
    },
    "telegram": {
        "rich_messages": None,
        "verification_table": None,
        "thinking_blocks": None,
        "max_table_rows": None,
        "compact_success": None,
        "max_detail_items": None,
    },
    "renderer": {
        "strategy": None,
        "edit_interval": None,
        "message_rollover_minutes": None,
        "stale_ttl_seconds": None,
        "redact_secrets": None,
        "mode": None,
        "style": None,
        "density": None,
        "agent_label": None,
    },
    "no_edit": {
        "interval_seconds": None,
        "min_new_events": None,
        "final_summary": None,
        "max_snapshots_per_turn": None,
    },
    "platforms": "platform_map",
    "defaults": "legacy_map",
}
PLATFORM_CONFIG_CONTRACT = {
    "enabled",
    "strategy",
    "lines",
    "preview_length",
    "edit_interval",
    "stale_ttl_seconds",
    "redact_secrets",
    "show_completed",
    "tools",
    "tools_enabled",
    "assistant",
    "assistant_enabled",
    "reasoning",
    "reasoning_enabled",
    "delegates",
    "delegates_enabled",
    "background_jobs",
    "background_jobs_enabled",
    "timestamp",
    "timestamp_format",
}
SNAPSHOT_DEFAULTS = {
    "slack",
    "signal",
    "bluebubbles",
    "weixin",
    "wecom",
    "wecom_callback",
    "dingtalk",
    "irc",
}
